package fi.muni.pv207.ticket;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BusinessCase implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BusinessCase() {
    }

}