package fi.muni.pv207.ticket;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BusinessCase implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Tile")
   private java.lang.String title;
   @org.kie.api.definition.type.Label(value = "Description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label(value = "Priority")
   private java.lang.Integer priority;
   @org.kie.api.definition.type.Label(value = "Email")
   private java.lang.String email;

   public BusinessCase()
   {
   }

   public java.lang.String getTitle()
   {
      return this.title;
   }

   public void setTitle(java.lang.String title)
   {
      this.title = title;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.Integer getPriority()
   {
      return this.priority;
   }

   public void setPriority(java.lang.Integer priority)
   {
      this.priority = priority;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public BusinessCase(java.lang.String title, java.lang.String description,
         java.lang.Integer priority, java.lang.String email)
   {
      this.title = title;
      this.description = description;
      this.priority = priority;
      this.email = email;
   }

}