package fi.muni.pv207.registration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Email")
   private java.lang.String email;
   @org.kie.api.definition.type.Label("Surname")
   private java.lang.String surname;

   @org.kie.api.definition.type.Label(value = "Subscription Till")
   private java.util.Date subscriptionTill;

   public Customer()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getSurname()
   {
      return this.surname;
   }

   public void setSurname(java.lang.String surname)
   {
      this.surname = surname;
   }

   public java.util.Date getSubscriptionTill()
   {
      return this.subscriptionTill;
   }

   public void setSubscriptionTill(java.util.Date subscriptionTill)
   {
      this.subscriptionTill = subscriptionTill;
   }

   public Customer(java.lang.String name, java.lang.String email,
         java.lang.String surname, java.util.Date subscriptionTill)
   {
      this.name = name;
      this.email = email;
      this.surname = surname;
      this.subscriptionTill = subscriptionTill;
   }

}