package fi.muni.pv207.registration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EvailValidationResult implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EvailValidationResult() {
    }

}